apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nl772an6t-go 
  janus-idp.io/tekton: nl772an6t-go
  backstage.io/kubernetes-id: nl772an6t-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nl772an6t-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml